-- Conversations with the assistant, their messages, and what each turn cost.
--
-- Three tables rather than one, because they answer three different questions:
-- what have I asked, what was said, and what did it cost.
--
-- Conversations belong to a user. Questions carry intent ("can I still afford
-- to build this", "what did I get wrong on that board") in a way a stock
-- adjustment does not, and an instance with a viewer account should not turn
-- into a log of what everyone has been wondering about. An admin who needs the
-- spend can read assistant_runs, which holds the cost without the content.
CREATE TABLE assistant_conversations (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- Taken from the first question, so the list is readable without opening
    -- anything. Not generated by the model: that would spend a request to
    -- title something the user may never look at again.
    title       TEXT        NOT NULL DEFAULT '',
    -- What the conversation was opened from, when it started as a popup on a
    -- part or a project. Nullable because the sidebar page has no subject.
    -- Deliberately not a foreign key: a conversation about a part you have
    -- since deleted is still a conversation worth keeping, and cascading it
    -- away would lose the record of what you asked and what it cost.
    subject_kind TEXT       CHECK (subject_kind IN ('part', 'project', 'board')),
    subject_id   UUID,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_assistant_conversations_user ON assistant_conversations(user_id, updated_at DESC);

CREATE TRIGGER trg_assistant_conversations_updated_at
    BEFORE UPDATE ON assistant_conversations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Messages, in order.
--
-- tool_calls and tool_results are stored, not just the prose, because a
-- provider needs them replayed to continue a conversation: Anthropic rejects an
-- assistant turn whose tool_use has no matching tool_result. Dropping them
-- would make every conversation single-turn in practice. They are also the only
-- record of where an answer's numbers came from.
CREATE TABLE assistant_messages (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID        NOT NULL REFERENCES assistant_conversations(id) ON DELETE CASCADE,
    -- seq rather than created_at ordering: two messages in one turn can land in
    -- the same millisecond, and their order is the whole meaning.
    seq             INTEGER     NOT NULL,
    role            TEXT        NOT NULL CHECK (role IN ('user', 'assistant')),
    content         TEXT        NOT NULL DEFAULT '',
    tool_calls      JSONB,
    tool_results    JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (conversation_id, seq)
);
CREATE INDEX idx_assistant_messages_conversation ON assistant_messages(conversation_id, seq);

-- One row per turn, whether or not the turn worked.
--
-- A failed turn still costs: the provider charges for the tokens it read before
-- the model ran out of output, or before a tool chain gave up. Recording only
-- successes would understate spend by exactly the turns worth investigating.
CREATE TABLE assistant_runs (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID        NOT NULL REFERENCES assistant_conversations(id) ON DELETE CASCADE,
    user_id         UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider        TEXT        NOT NULL,
    model           TEXT        NOT NULL DEFAULT '',
    -- How many provider requests the turn took. A turn that called four tools
    -- is five requests, and the cost is the sum, not the last one.
    rounds          INTEGER     NOT NULL DEFAULT 0,
    input_tokens    INTEGER     NOT NULL DEFAULT 0,
    output_tokens   INTEGER     NOT NULL DEFAULT 0,
    -- NULL means the model is not in the pricing table, which is different from
    -- zero. Zero is what a local model costs, and that is a fact worth keeping
    -- distinct from "unknown".
    cost_usd        NUMERIC(12, 6),
    -- Empty on success. Kept so a run that cost tokens and produced nothing
    -- explains itself.
    error           TEXT        NOT NULL DEFAULT '',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_assistant_runs_user ON assistant_runs(user_id, created_at DESC);
CREATE INDEX idx_assistant_runs_conversation ON assistant_runs(conversation_id, created_at);
